### ISSUE TITLE
EDD Software Licensing supported?

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/edd-per-product-emails#3]
Currently the "{license_keys} - Show all purchased licenses" tag is missing under the email text field.

Are they supported and not listed or no support until now?

**Comment by pippinsplugins** [comment]
Not yet but we could add it  easily.

**Comment by flowdee** [comment]
Would like it. Cause without it's not usable with licensing ;)

**Comment by sumobi** [comment]
The {license_keys} email tag should work, it's just not shown in the list (have fixed that). However, it wouldn't have been very useful since a per-product email would then show all license keys in that specific email. I've introduced a {license_key} email tag, similar to the one used by the software licensing plugin itself to only show the license key for the current download.

@pippinsplugins does this look ok to you? https://github.com/easydigitaldownloads/edd-per-product-emails/blob/master/includes/email-functions.php#L298-L325

**Comment by pippinsplugins** [comment]
@sumobi Better way to do it: https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/master/edd-software-licenses.php#L1585

Just call that function with first two parameters passed.

**Comment by sumobi** [comment]
@pippinsplugins excellent!

**Comment by sumobi** [comment]
@pippinsplugins The `get_license_by_purchase()` function only seems to retrieve 1 license for any given download. What if a download is purchased twice using quantities? There will be 2 license keys for the same download. Is this a scenario you've purposely blocked?

**Comment by pippinsplugins** [comment]
Not exactly blocked but also very rare.

**Comment by sumobi** [comment]
Ok I'll ignore it then :)

**Comment by sumobi** [comment]
Fixed via https://github.com/easydigitaldownloads/edd-per-product-emails/commit/3f1ec5e7bfce839e9872a67a13d60775f3dc25e0
